# Generated by Django 4.2.5 on 2023-11-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('owner_id', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
    ]
