# Generated by Django 4.2.5 on 2023-11-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedal', '0002_cycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='owner_id',
            field=models.IntegerField(default=1, verbose_name='Venue Owner'),
        ),
    ]
