# Generated by Django 4.2.5 on 2023-11-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedal', '0003_alter_cycle_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='cycle_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='owner_id',
            field=models.IntegerField(default=1, verbose_name='Cycle Owner'),
        ),
    ]
