# Generated by Django 4.2.5 on 2023-11-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedal', '0004_alter_cycle_cycle_img_alter_cycle_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='dop',
            field=models.DateTimeField(verbose_name='Date of Purchase'),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='owner_id',
            field=models.IntegerField(default=1, verbose_name='Cyle Owner'),
        ),
    ]
