# Generated by Django 4.2.5 on 2023-11-13 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedal', '0008_remove_appuser_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppUser',
        ),
    ]
