# Generated by Django 4.2.5 on 2023-11-13 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedal', '0012_alter_cycle_owner_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cycle',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
