# Generated by Django 4.2.5 on 2023-11-13 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedal', '0014_appuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedal.appuser'),
        ),
    ]
