# Generated by Django 4.2.5 on 2023-11-14 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedal', '0015_alter_cycle_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='cycle',
            name='is_avail',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cycle',
            name='no_of_rents',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cycle',
            name='total_stars',
            field=models.IntegerField(default=0),
        ),
    ]
