# Generated by Django 4.2.5 on 2023-11-14 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(max_length=2500)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.TextField(max_length=2500)),
                ('room', models.TextField(max_length=2500)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=2500)),
                ('cycle_id', models.TextField(max_length=1000)),
            ],
        ),
    ]
